import { DataManager } from '../services/DataManager';
import type { Trophy, TrophyCategory, UserProfile } from '../types';
import { TROPHIES_PER_PAGE, TROPHY_CATEGORIES } from '../scenes/TrophyScene';
import { addText, makeElement, type ScreenHandle } from './responsive';

export interface TrophyViewScene { selectedCategory: TrophyCategory; currentPage: number; allTrophies: readonly Trophy[]; switchCategory(category: TrophyCategory): void; calculateTrophyProgress(trophy: Trophy, profile: UserProfile): { current: number; target: number }; scene?: { start(key: string): void }; }

export function mountTrophyView(host: HTMLElement, scene: TrophyViewScene): ScreenHandle {
  const dm = DataManager.getInstance(); const profile = dm.getProfile();
  const shell = makeElement('main', 'screen-view support-view trophy-view'); shell.setAttribute('aria-labelledby', 'trophy-title');
  const head = makeElement('header', 'support-head'); const back = makeElement('button', 'support-back'); back.type = 'button'; back.textContent = '‹ 返回主頁'; back.addEventListener('click', () => scene.scene?.start('TitleScene')); head.append(back); addText(head, 'h1', '我的獎章', 'support-title').id = 'trophy-title'; shell.append(head);
  const unlocked = scene.allTrophies.filter((trophy) => Boolean(profile.trophies?.[trophy.id])).length; addText(shell, 'p', `已取得 ${unlocked} / ${scene.allTrophies.length} 個獎章`, 'trophy-summary');
  const tabs = makeElement('div', 'trophy-tabs'); tabs.setAttribute('role', 'tablist'); tabs.setAttribute('aria-label', '獎章分類');
  TROPHY_CATEGORIES.forEach((category, index) => { const selected = scene.selectedCategory === category.key; const tab = makeElement('button', 'trophy-tab'); tab.type = 'button'; tab.id = `trophy-tab-${category.key}`; tab.setAttribute('role', 'tab'); tab.setAttribute('aria-selected', String(selected)); tab.setAttribute('aria-controls', 'trophy-panel'); tab.tabIndex = selected ? 0 : -1; tab.textContent = `${category.icon} ${category.name}`; const select = (target = index) => { scene.switchCategory(TROPHY_CATEGORIES[target].key); mountTrophyView(host, scene); document.getElementById(`trophy-tab-${TROPHY_CATEGORIES[target].key}`)?.focus(); }; tab.addEventListener('click', () => select()); tab.addEventListener('keydown', (event) => { let target = index; if (event.key === 'ArrowRight') target = (index + 1) % TROPHY_CATEGORIES.length; else if (event.key === 'ArrowLeft') target = (index - 1 + TROPHY_CATEGORIES.length) % TROPHY_CATEGORIES.length; else if (event.key === 'Home') target = 0; else if (event.key === 'End') target = TROPHY_CATEGORIES.length - 1; else return; event.preventDefault(); select(target); }); tabs.append(tab); }); shell.append(tabs);
  const filtered = scene.allTrophies.filter((trophy) => trophy.category === scene.selectedCategory); const pages = Math.max(1, Math.ceil(filtered.length / TROPHIES_PER_PAGE)); scene.currentPage = Math.min(scene.currentPage, pages - 1); const page = filtered.slice(scene.currentPage * TROPHIES_PER_PAGE, (scene.currentPage + 1) * TROPHIES_PER_PAGE);
  const panel = makeElement('section'); panel.id = 'trophy-panel'; panel.setAttribute('role', 'tabpanel'); panel.setAttribute('aria-labelledby', `trophy-tab-${scene.selectedCategory}`); panel.tabIndex = 0; const list = makeElement('ul', 'trophy-grid'); page.forEach((trophy) => { const earned = Boolean(profile.trophies?.[trophy.id]); const progress = scene.calculateTrophyProgress(trophy, profile); const item = makeElement('li', `trophy-card${earned ? ' is-earned' : ''}`); item.innerHTML = `<span class="trophy-mark" aria-hidden="true">${earned ? (trophy.icon ?? '★') : '○'}</span>`; addText(item, 'h2', trophy.name); addText(item, 'p', trophy.description); const meter = makeElement('progress'); meter.max = progress.target; meter.value = Math.min(progress.current, progress.target); meter.setAttribute('aria-label', `${trophy.name}進度`); item.append(meter); addText(item, 'span', earned ? '已取得' : `${progress.current} / ${progress.target}`, 'trophy-progress'); list.append(item); }); panel.append(list); shell.append(panel);
  const nav = makeElement('nav', 'page-nav'); nav.setAttribute('aria-label', '獎章頁數'); const prev = makeElement('button'); prev.type = 'button'; prev.textContent = '上一頁'; prev.disabled = scene.currentPage === 0; prev.addEventListener('click', () => { scene.currentPage--; mountTrophyView(host, scene); }); addText(nav, 'span', `第 ${scene.currentPage + 1} / ${pages} 頁`); const next = makeElement('button'); next.type = 'button'; next.textContent = '下一頁'; next.disabled = scene.currentPage >= pages - 1; next.addEventListener('click', () => { scene.currentPage++; mountTrophyView(host, scene); }); nav.prepend(prev); nav.append(next); shell.append(nav); host.replaceChildren(shell); back.focus({ preventScroll: true }); return { destroy: () => shell.remove() };
}
