export interface CurriculumItem {
  id: string;
  subject: 'chinese' | 'english';
  category:
    | 'sentence_scramble'
    | 'vocabulary'
    | 'antonym'
    | 'measure_word'
    | 'punctuation'
    | 'radical'
    | 'homophone'
    | 'phonics'
    | 'sight_word'
    | 'plural'
    | 'preposition'
    | 'grammar';
  type: 'sentence_scramble' | 'multiple_choice';
  difficulty: 1 | 2 | 3 | 4;
  prompt: string;
  speakText: string;
  hintText?: string;
  // For sentence scramble:
  tokens?: string[];
  // For multiple choice:
  options?: string[];
  correctOptionIndex?: number;
  correctAnswer?: string;
}

export class CurriculumBank {
  // ==========================================
  // HONG KONG PRIMARY 1 CHINESE BANK (80+ items)
  // ==========================================
  static readonly CHINESE_BANK: readonly CurriculumItem[] = [
    // --- Level 1: Sentence Scramble ---
    {
      id: 'zh_scramble_101',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '姐姐吃餅乾。',
      tokens: ['姐姐', '吃', '餅乾', '。'],
      hintText: '提示：主語是「姐姐」',
    },
    {
      id: 'zh_scramble_102',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '哥哥去上學。',
      tokens: ['哥哥', '去', '上學', '。'],
      hintText: '提示：主語是「哥哥」',
    },
    {
      id: 'zh_scramble_103',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '小貓愛吃魚。',
      tokens: ['小貓', '愛', '吃魚', '。'],
      hintText: '提示：誰愛吃魚？',
    },
    {
      id: 'zh_scramble_104',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '爸爸看報紙。',
      tokens: ['爸爸', '看', '報紙', '。'],
      hintText: '提示：動作是「看」',
    },
    {
      id: 'zh_scramble_105',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '弟弟玩玩具。',
      tokens: ['弟弟', '玩', '玩具', '。'],
      hintText: '提示：主語是「弟弟」',
    },
    {
      id: 'zh_scramble_106',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '小狗在跑。',
      tokens: ['小狗', '在', '跑', '。'],
      hintText: '提示：主語是「小狗」',
    },
    {
      id: 'zh_scramble_107',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '太陽出來了。',
      tokens: ['太陽', '出來', '了', '。'],
      hintText: '提示：甚麼出來了？',
    },
    {
      id: 'zh_scramble_108',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '媽媽煮晚餐。',
      tokens: ['媽媽', '煮', '晚餐', '。'],
      hintText: '提示：主語是「媽媽」',
    },

    // --- Level 2: Sentence Scramble ---
    {
      id: 'zh_scramble_201',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '老師拿粉筆寫字。',
      tokens: ['老師', '拿', '粉筆', '寫字', '。'],
      hintText: '提示：誰拿粉筆？',
    },
    {
      id: 'zh_scramble_202',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '小鳥在樹上唱歌。',
      tokens: ['小鳥', '在', '樹上', '唱歌', '。'],
      hintText: '提示：小鳥在哪裡唱歌？',
    },
    {
      id: 'zh_scramble_203',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '我們在公園跑步。',
      tokens: ['我們', '在', '公園', '跑步', '。'],
      hintText: '提示：地點是「公園」',
    },
    {
      id: 'zh_scramble_204',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '妹妹在房間畫畫。',
      tokens: ['妹妹', '在', '房間', '畫畫', '。'],
      hintText: '提示：妹妹在哪裡？',
    },
    {
      id: 'zh_scramble_205',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '弟弟喜歡喝牛奶。',
      tokens: ['弟弟', '喜歡', '喝', '牛奶', '。'],
      hintText: '提示：動作是「喜歡喝」',
    },
    {
      id: 'zh_scramble_206',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '青蛙在池塘跳躍。',
      tokens: ['青蛙', '在', '池塘', '跳躍', '。'],
      hintText: '提示：主語是「青蛙」',
    },
    {
      id: 'zh_scramble_207',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '花朵在陽光下開放。',
      tokens: ['花朵', '在', '陽光下', '開放', '。'],
      hintText: '提示：甚麼在開放？',
    },
    {
      id: 'zh_scramble_208',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '同學在操場踢球。',
      tokens: ['同學', '在', '操場', '踢球', '。'],
      hintText: '提示：地點是「操場」',
    },

    // --- Level 3: Sentence Scramble ---
    {
      id: 'zh_scramble_301',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '我看見一隻可愛的貓咪。',
      tokens: ['我看見', '一隻', '可愛的', '貓咪', '。'],
      hintText: '提示：主語開頭「我看見」',
    },
    {
      id: 'zh_scramble_302',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '爸爸每天坐巴士上班。',
      tokens: ['爸爸', '每天', '坐巴士', '上班', '。'],
      hintText: '提示：爸爸每天做甚麼？',
    },
    {
      id: 'zh_scramble_303',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '小魚在清澈的河水裡游泳。',
      tokens: ['小魚', '在', '清澈的', '河水裡', '游泳', '。'],
      hintText: '提示：小魚在哪裡？',
    },
    {
      id: 'zh_scramble_304',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '叔叔送給我一本故事書。',
      tokens: ['叔叔', '送給我', '一本', '故事書', '。'],
      hintText: '提示：誰送給誰？',
    },
    {
      id: 'zh_scramble_305',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '花園裡開滿了美麗的鮮花。',
      tokens: ['花園裡', '開滿了', '美麗的', '鮮花', '。'],
      hintText: '提示：地點開頭「花園裡」',
    },
    {
      id: 'zh_scramble_306',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '我們一起到圖書館看書。',
      tokens: ['我們', '一起', '到圖書館', '看書', '。'],
      hintText: '提示：大家一起去哪裡？',
    },
    {
      id: 'zh_scramble_307',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '天空中飄著潔白的雲朵。',
      tokens: ['天空中', '飄著', '潔白的', '雲朵', '。'],
      hintText: '提示：天空中飄著甚麼？',
    },

    // --- Level 4: Sentence Scramble ---
    {
      id: 'zh_scramble_401',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '放學後，我和同學一起走路回家。',
      tokens: ['放學後', '，', '我和同學', '一起', '走路回家', '。'],
      hintText: '提示：時間狀語「放學後」開頭',
    },
    {
      id: 'zh_scramble_402',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '春風吹來，樹葉輕輕地搖擺。',
      tokens: ['春風吹來', '，', '樹葉', '輕輕地', '搖擺', '。'],
      hintText: '提示：前半句「春風吹來」',
    },
    {
      id: 'zh_scramble_403',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '小燕子在藍藍的天空中自由地飛翔。',
      tokens: ['小燕子', '在', '藍藍的', '天空中', '自由地', '飛翔', '。'],
      hintText: '提示：主語是「小燕子」',
    },
    {
      id: 'zh_scramble_404',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '媽媽在廚房做了香甜的蘋果派。',
      tokens: ['媽媽', '在廚房', '做了', '香甜的', '蘋果派', '。'],
      hintText: '提示：誰在哪裡做了甚麼？',
    },
    {
      id: 'zh_scramble_405',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '下雨了，路上的行人都撐起了雨傘。',
      tokens: ['下雨了', '，', '路上的行人', '都撐起了', '雨傘', '。'],
      hintText: '提示：「下雨了」排在最前',
    },
    {
      id: 'zh_scramble_406',
      subject: 'chinese',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: '重組句子：請把字詞排列成通順的句子。',
      speakText: '我們在操場上快樂地跑步。',
      tokens: ['我們', '在操場上', '快樂地', '跑步', '。'],
      hintText: '提示：先找出人物「我們」',
    },

    // --- Antonyms (反義詞) ---
    {
      id: 'zh_ant_101',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出「大」的反義詞：',
      speakText: '請問「大」的反義詞是甚麼？',
      options: ['小', '多', '高', '長'],
      correctOptionIndex: 0,
      correctAnswer: '小',
      hintText: '提示：大象很大，螞蟻很……',
    },
    {
      id: 'zh_ant_102',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出「上」的反義詞：',
      speakText: '請問「上」的反義詞是甚麼？',
      options: ['下', '左', '前', '外'],
      correctOptionIndex: 0,
      correctAnswer: '下',
      hintText: '提示：上山對應……',
    },
    {
      id: 'zh_ant_103',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出「多」的反義詞：',
      speakText: '請問「多」的反義詞是甚麼？',
      options: ['少', '矮', '短', '輕'],
      correctOptionIndex: 0,
      correctAnswer: '少',
      hintText: '提示：數量很多或很……',
    },
    {
      id: 'zh_ant_104',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出「開」的反義詞：',
      speakText: '請問「開」的反義詞是甚麼？',
      options: ['關', '跑', '走', '看'],
      correctOptionIndex: 0,
      correctAnswer: '關',
      hintText: '提示：開門對應……',
    },
    {
      id: 'zh_ant_201',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「高」的反義詞：',
      speakText: '請問「高」的反義詞是甚麼？',
      options: ['矮', '短', '細', '小'],
      correctOptionIndex: 0,
      correctAnswer: '矮',
      hintText: '提示：大樹很高，小草很……',
    },
    {
      id: 'zh_ant_202',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「長」的反義詞：',
      speakText: '請問「長」的反義詞是甚麼？',
      options: ['短', '矮', '小', '少'],
      correctOptionIndex: 0,
      correctAnswer: '短',
      hintText: '提示：長尺對應……',
    },
    {
      id: 'zh_ant_203',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「快」的反義詞：',
      speakText: '請問「快」的反義詞是甚麼？',
      options: ['慢', '重', '退', '靜'],
      correctOptionIndex: 0,
      correctAnswer: '慢',
      hintText: '提示：兔子跑得快，烏龜爬得……',
    },
    {
      id: 'zh_ant_204',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「前」的反義詞：',
      speakText: '請問「前」的反義詞是甚麼？',
      options: ['後', '左', '右', '下'],
      correctOptionIndex: 0,
      correctAnswer: '後',
      hintText: '提示：前面對應……',
    },
    {
      id: 'zh_ant_205',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「冷」的反義詞：',
      speakText: '請問「冷」的反義詞是甚麼？',
      options: ['熱', '溫', '暖', '涼'],
      correctOptionIndex: 0,
      correctAnswer: '熱',
      hintText: '提示：冬天冷，夏天……',
    },
    {
      id: 'zh_ant_206',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出「早」的反義詞：',
      speakText: '請問「早」的反義詞是甚麼？',
      options: ['晚', '夜', '後', '長'],
      correctOptionIndex: 0,
      correctAnswer: '晚',
      hintText: '提示：早晨對應傍……',
    },
    {
      id: 'zh_ant_301',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「輕」的反義詞：',
      speakText: '請問「輕」的反義詞是甚麼？',
      options: ['重', '厚', '硬', '大'],
      correctOptionIndex: 0,
      correctAnswer: '重',
      hintText: '提示：羽毛很輕，石頭很……',
    },
    {
      id: 'zh_ant_302',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「新」的反義詞：',
      speakText: '請問「新」的反義詞是甚麼？',
      options: ['舊', '破', '爛', '壞'],
      correctOptionIndex: 0,
      correctAnswer: '舊',
      hintText: '提示：新衣服對應……',
    },
    {
      id: 'zh_ant_303',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「胖」的反義詞：',
      speakText: '請問「胖」的反義詞是甚麼？',
      options: ['瘦', '小', '弱', '細'],
      correctOptionIndex: 0,
      correctAnswer: '瘦',
      hintText: '提示：身材胖對應……',
    },
    {
      id: 'zh_ant_304',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「遠」的反義詞：',
      speakText: '請問「遠」的反義詞是甚麼？',
      options: ['近', '旁', '鄰', '貼'],
      correctOptionIndex: 0,
      correctAnswer: '近',
      hintText: '提示：距離很遠或很……',
    },
    {
      id: 'zh_ant_305',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「美」的反義詞：',
      speakText: '請問「美」的反義詞是甚麼？',
      options: ['醜', '惡', '壞', '差'],
      correctOptionIndex: 0,
      correctAnswer: '醜',
      hintText: '提示：美麗對應……',
    },
    {
      id: 'zh_ant_306',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出「黑」的反義詞：',
      speakText: '請問「黑」的反義詞是甚麼？',
      options: ['白', '亮', '光', '明'],
      correctOptionIndex: 0,
      correctAnswer: '白',
      hintText: '提示：黑板與……色粉筆',
    },
    {
      id: 'zh_ant_401',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「亮」的反義詞：',
      speakText: '請問「亮」的反義詞是甚麼？',
      options: ['暗', '黑', '陰', '深'],
      correctOptionIndex: 0,
      correctAnswer: '暗',
      hintText: '提示：光線明亮對應……',
    },
    {
      id: 'zh_ant_402',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「甜」的反義詞：',
      speakText: '請問「甜」的反義詞是甚麼？',
      options: ['苦', '酸', '辣', '鹹'],
      correctOptionIndex: 0,
      correctAnswer: '苦',
      hintText: '提示：糖果甜，苦瓜……',
    },
    {
      id: 'zh_ant_403',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「粗」的反義詞：',
      speakText: '請問「粗」的反義詞是甚麼？',
      options: ['細', '大', '短', '厚'],
      correctOptionIndex: 0,
      correctAnswer: '細',
      hintText: '提示：樹幹很粗，樹枝很……',
    },
    {
      id: 'zh_ant_404',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「深」的反義詞：',
      speakText: '請問「深」的反義詞是甚麼？',
      options: ['淺', '平', '低', '矮'],
      correctOptionIndex: 0,
      correctAnswer: '淺',
      hintText: '提示：深水區對應……水區',
    },
    {
      id: 'zh_ant_405',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「軟」的反義詞：',
      speakText: '請問「軟」的反義詞是甚麼？',
      options: ['硬', '堅', '強', '固'],
      correctOptionIndex: 0,
      correctAnswer: '硬',
      hintText: '提示：棉花很軟，石頭很……',
    },
    {
      id: 'zh_ant_406',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「真」的反義詞：',
      speakText: '請問「真」的反義詞是甚麼？',
      options: ['假', '偽', '錯', '虛'],
      correctOptionIndex: 0,
      correctAnswer: '假',
      hintText: '提示：真假難辨',
    },
    {
      id: 'zh_ant_407',
      subject: 'chinese',
      category: 'antonym',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出「厚」的反義詞：',
      speakText: '請問「厚」的反義詞是甚麼？',
      options: ['薄', '細', '扁', '輕'],
      correctOptionIndex: 0,
      correctAnswer: '薄',
      hintText: '提示：字典很厚，紙張很……',
    },

    // --- Measure Words (量詞) ---
    {
      id: 'zh_mw_101',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '填上合適的量詞：一（　）小狗',
      speakText: '一甚麼小狗？',
      options: ['隻', '個', '本', '張'],
      correctOptionIndex: 0,
      correctAnswer: '隻',
      hintText: '提示：小動物通常用……',
    },
    {
      id: 'zh_mw_102',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '填上合適的量詞：一（　）蘋果',
      speakText: '一甚麼蘋果？',
      options: ['個', '隻', '條', '本'],
      correctOptionIndex: 0,
      correctAnswer: '個',
      hintText: '提示：圓形的水果常用「個」',
    },
    {
      id: 'zh_mw_103',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '填上合適的量詞：一（　）書本',
      speakText: '一甚麼書本？',
      options: ['本', '張', '支', '件'],
      correctOptionIndex: 0,
      correctAnswer: '本',
      hintText: '提示：故事書、課本用……',
    },
    {
      id: 'zh_mw_104',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '填上合適的量詞：一（　）鉛筆',
      speakText: '一甚麼鉛筆？',
      options: ['支', '本', '張', '把'],
      correctOptionIndex: 0,
      correctAnswer: '支',
      hintText: '提示：細長文具用「支」',
    },
    {
      id: 'zh_mw_201',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）衣服',
      speakText: '一甚麼衣服？',
      options: ['件', '條', '張', '套'],
      correctOptionIndex: 0,
      correctAnswer: '件',
      hintText: '提示：上衣、外套用……',
    },
    {
      id: 'zh_mw_202',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）雨傘',
      speakText: '一甚麼雨傘？',
      options: ['把', '支', '條', '張'],
      correctOptionIndex: 0,
      correctAnswer: '把',
      hintText: '提示：有手柄的用「把」',
    },
    {
      id: 'zh_mw_203',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）大樹',
      speakText: '一甚麼大樹？',
      options: ['棵', '枝', '條', '把'],
      correctOptionIndex: 0,
      correctAnswer: '棵',
      hintText: '提示：植物、樹木用「棵」',
    },
    {
      id: 'zh_mw_204',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）花朵',
      speakText: '一甚麼花朵？',
      options: ['朵', '個', '條', '片'],
      correctOptionIndex: 0,
      correctAnswer: '朵',
      hintText: '提示：美麗的花……',
    },
    {
      id: 'zh_mw_205',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）小魚',
      speakText: '一甚麼小魚？',
      options: ['條', '隻', '個', '頭'],
      correctOptionIndex: 0,
      correctAnswer: '條',
      hintText: '提示：長形生物用「條」',
    },
    {
      id: 'zh_mw_206',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '填上合適的量詞：一（　）大象',
      speakText: '一甚麼大象？',
      options: ['頭', '隻', '條', '座'],
      correctOptionIndex: 0,
      correctAnswer: '頭',
      hintText: '提示：體型龐大的動物用「頭」',
    },
    {
      id: 'zh_mw_301',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）書桌',
      speakText: '一甚麼書桌？',
      options: ['張', '把', '個', '件'],
      correctOptionIndex: 0,
      correctAnswer: '張',
      hintText: '提示：平面的傢俬用「張」',
    },
    {
      id: 'zh_mw_302',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）輪船',
      speakText: '一甚麼輪船？',
      options: ['艘', '架', '輛', '隻'],
      correctOptionIndex: 0,
      correctAnswer: '艘',
      hintText: '提示：船隻專用量詞「艘」',
    },
    {
      id: 'zh_mw_303',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）飛機',
      speakText: '一甚麼飛機？',
      options: ['架', '部', '艘', '輛'],
      correctOptionIndex: 0,
      correctAnswer: '架',
      hintText: '提示：飛機常用「架」',
    },
    {
      id: 'zh_mw_304',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）巴士',
      speakText: '一甚麼巴士？',
      options: ['輛', '架', '艘', '隻'],
      correctOptionIndex: 0,
      correctAnswer: '輛',
      hintText: '提示：陸地車輛常用「輛」',
    },
    {
      id: 'zh_mw_305',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）牛奶',
      speakText: '一甚麼牛奶？',
      options: ['杯', '碗', '盤', '粒'],
      correctOptionIndex: 0,
      correctAnswer: '杯',
      hintText: '提示：盛載飲料用「杯」',
    },
    {
      id: 'zh_mw_306',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '填上合適的量詞：一（　）糖果',
      speakText: '一甚麼糖果？',
      options: ['顆', '張', '支', '條'],
      correctOptionIndex: 0,
      correctAnswer: '顆',
      hintText: '提示：顆粒狀物品用「顆」',
    },
    {
      id: 'zh_mw_401',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）皮鞋',
      speakText: '一甚麼皮鞋？',
      options: ['雙', '張', '條', '座'],
      correctOptionIndex: 0,
      correctAnswer: '雙',
      hintText: '提示：成雙成對的鞋襪用「雙」',
    },
    {
      id: 'zh_mw_402',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）小鳥在天空飛',
      speakText: '一甚麼小鳥在天空飛？',
      options: ['群', '排', '串', '座'],
      correctOptionIndex: 0,
      correctAnswer: '群',
      hintText: '提示：聚集在一起的動物用「群」',
    },
    {
      id: 'zh_mw_403',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）香蕉',
      speakText: '一甚麼香蕉？',
      options: ['串', '張', '把', '座'],
      correctOptionIndex: 0,
      correctAnswer: '串',
      hintText: '提示：連在一起的水果用「串」',
    },
    {
      id: 'zh_mw_404',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）大山',
      speakText: '一甚麼大山？',
      options: ['座', '個', '頭', '條'],
      correctOptionIndex: 0,
      correctAnswer: '座',
      hintText: '提示：高大固定物體用「座」',
    },
    {
      id: 'zh_mw_405',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）羽毛',
      speakText: '一甚麼羽毛？',
      options: ['根', '支', '條', '片'],
      correctOptionIndex: 0,
      correctAnswer: '根',
      hintText: '提示：細長輕巧物體用「根」',
    },
    {
      id: 'zh_mw_406',
      subject: 'chinese',
      category: 'measure_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '填上合適的量詞：一（　）椅子',
      speakText: '一甚麼椅子？',
      options: ['把', '雙', '隻', '本'],
      correctOptionIndex: 0,
      correctAnswer: '把',
      hintText: '提示：有靠背手柄的椅子用「把」',
    },

    // --- Punctuation (標點符號) ---
    {
      id: 'zh_punc_101',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '「太陽出來了（　）」括號內應填上甚麼標點？',
      speakText: '太陽出來了後面應填上甚麼標點？',
      options: ['。', '？', '！', '，'],
      correctOptionIndex: 0,
      correctAnswer: '。',
      hintText: '提示：完整陳述句使用句號',
    },
    {
      id: 'zh_punc_102',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '「今天天氣晴朗（　）」括號內應填上甚麼標點？',
      speakText: '今天天氣晴朗後面應填上甚麼標點？',
      options: ['。', '？', '！', '、'],
      correctOptionIndex: 0,
      correctAnswer: '。',
      hintText: '提示：陳述事實結尾用句號',
    },
    {
      id: 'zh_punc_201',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '「你叫甚麼名字（　）」括號內應填上甚麼標點？',
      speakText: '你叫甚麼名字後面應填上甚麼標點？',
      options: ['？', '。', '！', '，'],
      correctOptionIndex: 0,
      correctAnswer: '？',
      hintText: '提示：發出疑問使用問號',
    },
    {
      id: 'zh_punc_202',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '「這是你的書包嗎（　）」括號內應填上甚麼標點？',
      speakText: '這是你的書包嗎後面應填上甚麼標點？',
      options: ['？', '。', '！', '、'],
      correctOptionIndex: 0,
      correctAnswer: '？',
      hintText: '提示：帶有疑問詞「嗎」用問號',
    },
    {
      id: 'zh_punc_301',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '「公園裡的花朵真美麗啊（　）」括號內應填上甚麼標點？',
      speakText: '公園裡的花朵真美麗啊後面應填上甚麼標點？',
      options: ['！', '。', '？', '，'],
      correctOptionIndex: 0,
      correctAnswer: '！',
      hintText: '提示：抒發強烈讚美感情用感嘆號',
    },
    {
      id: 'zh_punc_302',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '「太好了，我們得獎了（　）」括號內應填上甚麼標點？',
      speakText: '太好了，我們得獎了後面應填上甚麼標點？',
      options: ['！', '？', '。', '、'],
      correctOptionIndex: 0,
      correctAnswer: '！',
      hintText: '提示：歡呼喜悅語氣用感嘆號',
    },
    {
      id: 'zh_punc_401',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '「媽媽問我（　）『功課做好了嗎？』」括號內應填上甚麼標點？',
      speakText: '媽媽問我後面接引號前應填甚麼標點？',
      options: ['：', '，', '。', '！'],
      correctOptionIndex: 0,
      correctAnswer: '：',
      hintText: '提示：引出說話內容使用冒號',
    },
    {
      id: 'zh_punc_402',
      subject: 'chinese',
      category: 'punctuation',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '「書包裡有筆盒、書本（　）水壺和毛巾。」括號內應填上甚麼標點？',
      speakText: '書包裡有筆盒、書本、水壺和毛巾，括號內應填上甚麼標點？',
      options: ['、', '，', '。', '！'],
      correctOptionIndex: 0,
      correctAnswer: '、',
      hintText: '提示：同類詞語列舉使用頓號',
    },

    // --- Vocabulary & Character Recognition (認字) ---
    {
      id: 'zh_vocab_101',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出帶有「口」部首的字：',
      speakText: '請問哪一個字有口字旁？',
      options: ['吃', '跑', '樹', '花'],
      correctOptionIndex: 0,
      correctAnswer: '吃',
      hintText: '提示：與吃東西有關的字',
    },
    {
      id: 'zh_vocab_102',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出帶有「木」部首的字：',
      speakText: '請問哪一個字有木字旁？',
      options: ['林', '江', '媽', '玩'],
      correctOptionIndex: 0,
      correctAnswer: '林',
      hintText: '提示：樹木聚集叫樹……',
    },
    {
      id: 'zh_vocab_201',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '「氵」（三點水）部首的字通常與甚麼有關？',
      speakText: '三點水部首的字通常與甚麼有關？',
      options: ['河流與水', '樹木與花', '說話與語言', '奔跑與運動'],
      correctOptionIndex: 0,
      correctAnswer: '河流與水',
      hintText: '提示：江、河、湖、海都帶有三點水',
    },
    {
      id: 'zh_vocab_202',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '「日」字旁的字通常與甚麼有關？',
      speakText: '日字旁的字通常與甚麼有關？',
      options: ['太陽與時間', '水與海洋', '食物與吃', '金屬與工具'],
      correctOptionIndex: 0,
      correctAnswer: '太陽與時間',
      hintText: '提示：日代表太陽，如「晴、明、時、晨」',
    },
    {
      id: 'zh_vocab_301',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '「明」字是由哪兩個字合起來組成的？',
      speakText: '明字是由哪兩個字組成的？',
      options: ['日 和 月', '木 和 目', '口 和 十', '人 和 門'],
      correctOptionIndex: 0,
      correctAnswer: '日 和 月',
      hintText: '提示：太陽和月亮帶來光明',
    },
    {
      id: 'zh_vocab_401',
      subject: 'chinese',
      category: 'vocabulary',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '下列哪一個字的讀音與「青」相同或相近？',
      speakText: '下列哪一個字的讀音與青相同？',
      options: ['清', '春', '靜', '情'],
      correctOptionIndex: 0,
      correctAnswer: '清',
      hintText: '提示：清水、清潔的清',
    },

    // --- Radicals & Character Structure (部首與字形) ---
    {
      id: 'zh_rad_101',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出「打、拍、提」的共同部首：',
      speakText: '請問打、拍、提的共同部首是甚麼？',
      options: ['扌（提手旁）', '⻊（足字旁）', '氵（三點水）', '口（口字旁）'],
      correctOptionIndex: 0,
      correctAnswer: '扌（提手旁）',
      hintText: '提示：都跟手部動作有關',
    },
    {
      id: 'zh_rad_102',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出「跑、跳、踢」的共同部首：',
      speakText: '請問跑、跳、踢的共同部首是甚麼？',
      options: ['⻊（足字旁）', '扌（提手旁）', '木（木字旁）', '日（日字旁）'],
      correctOptionIndex: 0,
      correctAnswer: '⻊（足字旁）',
      hintText: '提示：都跟腳部動作有關',
    },
    {
      id: 'zh_rad_103',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出「江、河、海」的共同部首：',
      speakText: '請問江、河、海的共同部首是甚麼？',
      options: ['氵（三點水）', '木（木字旁）', '火（火字旁）', '艹（草字頭）'],
      correctOptionIndex: 0,
      correctAnswer: '氵（三點水）',
      hintText: '提示：都跟水流或液體有關',
    },
    {
      id: 'zh_rad_104',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '找出「花、草、苗」的共同部首：',
      speakText: '請問花、草、苗的共同部首是甚麼？',
      options: ['艹（草字頭）', '木（木字旁）', '氵（三點水）', '口（口字旁）'],
      correctOptionIndex: 0,
      correctAnswer: '艹（草字頭）',
      hintText: '提示：都跟植物花草有關',
    },
    {
      id: 'zh_rad_201',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '下列哪一個字帶有「口」（口字旁）？',
      speakText: '下列哪一個字帶有口字旁？',
      options: ['唱', '跳', '跑', '打'],
      correctOptionIndex: 0,
      correctAnswer: '唱',
      hintText: '提示：唱歌要用嘴巴',
    },
    {
      id: 'zh_rad_202',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '下列哪一個字帶有「木」（木字旁）？',
      speakText: '下列哪一個字帶有木字旁？',
      options: ['樹', '清', '媽', '眼'],
      correctOptionIndex: 0,
      correctAnswer: '樹',
      hintText: '提示：大樹是木頭做的植物',
    },
    {
      id: 'zh_rad_203',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '下列哪一個字帶有「目」（目字旁）？',
      speakText: '下列哪一個字帶有目字旁？',
      options: ['眼', '耳', '口', '手'],
      correctOptionIndex: 0,
      correctAnswer: '眼',
      hintText: '提示：「目」就是眼睛的意思',
    },
    {
      id: 'zh_rad_301',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '「想、念、思」這些字的部首是甚麼？',
      speakText: '請問想、念、思這些字的部首是甚麼？',
      options: ['心（心字底）', '日（日字旁）', '言（言字旁）', '目（目字旁）'],
      correctOptionIndex: 0,
      correctAnswer: '心（心字底）',
      hintText: '提示：思考與心情都在心裡',
    },
    {
      id: 'zh_rad_302',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '「講、說、話」這些字都跟甚麼有關？',
      speakText: '請問講、說、話這些字都跟甚麼有關？',
      options: ['語言與說話', '走路奔跑', '游泳玩水', '拍手打球'],
      correctOptionIndex: 0,
      correctAnswer: '語言與說話',
      hintText: '提示：部首都是言字旁',
    },
    {
      id: 'zh_rad_401',
      subject: 'chinese',
      category: 'radical',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '「晴、晨、晚」這些字都帶有甚麼部首？',
      speakText: '請問晴、晨、晚這些字帶有甚麼部首？',
      options: ['日（日字旁）', '月（月字旁）', '火（火字旁）', '水（水字旁）'],
      correctOptionIndex: 0,
      correctAnswer: '日（日字旁）',
      hintText: '提示：都跟太陽與時間有關',
    },

    // --- Homophones & Word Selection (同音字與選詞填空) ---
    {
      id: 'zh_homo_101',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出正確的字：「小明正（　）房間裡溫習功課。」',
      speakText: '小明正在房間裡溫習功課，括號內應填甚麼字？',
      options: ['在', '再', '仔', '栽'],
      correctOptionIndex: 0,
      correctAnswer: '在',
      hintText: '提示：表示身處某個地方用「在」',
    },
    {
      id: 'zh_homo_102',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出正確的字：「放學了，明天我們（　）一起玩。」',
      speakText: '明天我們再一起玩，括號內應填甚麼字？',
      options: ['再', '在', '載', '災'],
      correctOptionIndex: 0,
      correctAnswer: '再',
      hintText: '提示：表示再次、又一次用「再」',
    },
    {
      id: 'zh_homo_103',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出正確的字：「巴士上有許多（　）位。」',
      speakText: '巴士上有許多座位，括號內應填甚麼字？',
      options: ['座', '坐', '作', '做'],
      correctOptionIndex: 0,
      correctAnswer: '座',
      hintText: '提示：名詞「座位」用座',
    },
    {
      id: 'zh_homo_104',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: '選出正確的字：「請大家安靜地（　）在椅子上。」',
      speakText: '請大家安靜地坐在椅子上，括號內應填甚麼字？',
      options: ['坐', '座', '作', '左'],
      correctOptionIndex: 0,
      correctAnswer: '坐',
      hintText: '提示：動作「坐下」用坐',
    },
    {
      id: 'zh_homo_201',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出正確的字：「妹妹穿著漂亮的裙子，（　）非常高興。」',
      speakText: '妹妹穿著漂亮的裙子，她非常高興，括號內應填甚麼字？',
      options: ['她', '他', '它', '牠'],
      correctOptionIndex: 0,
      correctAnswer: '她',
      hintText: '提示：女字旁的「她」指女性',
    },
    {
      id: 'zh_homo_202',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出正確的字：「小狗在草地上跑，（　）的尾巴搖來搖去。」',
      speakText: '小狗在草地上跑，牠的尾巴搖來搖去，括號內應填甚麼字？',
      options: ['牠', '他', '她', '太'],
      correctOptionIndex: 0,
      correctAnswer: '牠',
      hintText: '提示：牛字旁的「牠」指動物',
    },
    {
      id: 'zh_homo_203',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: '選出正確的字：「哥哥是個好學生，（　）每天準時上學。」',
      speakText: '哥哥是個好學生，他每天準時上學，括號內應填甚麼字？',
      options: ['他', '她', '它', '太'],
      correctOptionIndex: 0,
      correctAnswer: '他',
      hintText: '提示：單人旁的「他」指男性',
    },
    {
      id: 'zh_homo_301',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出正確的字：「爸爸在文具店（　）了一支新鉛筆給我。」',
      speakText: '爸爸在文具店買了一支新鉛筆給我，括號內應填甚麼字？',
      options: ['買', '賣', '埋', '邁'],
      correctOptionIndex: 0,
      correctAnswer: '買',
      hintText: '提示：付錢購物叫「買」',
    },
    {
      id: 'zh_homo_302',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: '選出正確的字：「水果攤的叔叔正在（　）香甜的蘋果。」',
      speakText: '水果攤的叔叔正在賣香甜的蘋果，括號內應填甚麼字？',
      options: ['賣', '買', '邁', '埋'],
      correctOptionIndex: 0,
      correctAnswer: '賣',
      hintText: '提示：出售物品叫「賣」',
    },
    {
      id: 'zh_homo_401',
      subject: 'chinese',
      category: 'homophone',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: '選出正確的字：「小鳥在天空中快活（　）飛翔。」',
      speakText: '小鳥在天空中快活地飛翔，括號內應填甚麼字？',
      options: ['地', '的', '得', '第'],
      correctOptionIndex: 0,
      correctAnswer: '地',
      hintText: '提示：修飾動作（飛翔）使用「地」',
    },
  ];

  // ==========================================
  // HONG KONG PRIMARY 1 ENGLISH BANK (75+ items)
  // ==========================================
  static readonly ENGLISH_BANK: readonly CurriculumItem[] = [
    // --- Level 1: Sentence Scramble ---
    {
      id: 'en_scramble_101',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'I like apples.',
      tokens: ['I', 'like', 'apples', '.'],
      hintText: 'Hint: Starts with "I"',
    },
    {
      id: 'en_scramble_102',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The cat is sleeping.',
      tokens: ['The', 'cat', 'is', 'sleeping', '.'],
      hintText: 'Hint: Starts with "The"',
    },
    {
      id: 'en_scramble_103',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'She has a bag.',
      tokens: ['She', 'has', 'a', 'bag', '.'],
      hintText: 'Hint: Starts with "She"',
    },
    {
      id: 'en_scramble_104',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'It is a sunny day.',
      tokens: ['It', 'is', 'a', 'sunny', 'day', '.'],
      hintText: 'Hint: Starts with "It"',
    },
    {
      id: 'en_scramble_105',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'This is a book.',
      tokens: ['This', 'is', 'a', 'book', '.'],
      hintText: 'Hint: Starts with "This"',
    },
    {
      id: 'en_scramble_106',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'He is my dad.',
      tokens: ['He', 'is', 'my', 'dad', '.'],
      hintText: 'Hint: Starts with "He"',
    },
    {
      id: 'en_scramble_107',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The dog is brown.',
      tokens: ['The', 'dog', 'is', 'brown', '.'],
      hintText: 'Hint: The dog is...',
    },
    {
      id: 'en_scramble_108',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 1,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'I see a bird.',
      tokens: ['I', 'see', 'a', 'bird', '.'],
      hintText: 'Hint: Starts with "I"',
    },

    // --- Level 2: Sentence Scramble ---
    {
      id: 'en_scramble_201',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'We go to school together.',
      tokens: ['We', 'go', 'to', 'school', 'together', '.'],
      hintText: 'Hint: Starts with "We"',
    },
    {
      id: 'en_scramble_202',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The bird is in the tree.',
      tokens: ['The', 'bird', 'is', 'in', 'the', 'tree', '.'],
      hintText: 'Hint: Where is the bird?',
    },
    {
      id: 'en_scramble_203',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'My mother is a teacher.',
      tokens: ['My', 'mother', 'is', 'a', 'teacher', '.'],
      hintText: 'Hint: Starts with "My"',
    },
    {
      id: 'en_scramble_204',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The boy can swim fast.',
      tokens: ['The', 'boy', 'can', 'swim', 'fast', '.'],
      hintText: 'Hint: The boy can...',
    },
    {
      id: 'en_scramble_205',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'She has two red apples.',
      tokens: ['She', 'has', 'two', 'red', 'apples', '.'],
      hintText: 'Hint: She has two...',
    },
    {
      id: 'en_scramble_206',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'Look at the blue sky.',
      tokens: ['Look', 'at', 'the', 'blue', 'sky', '.'],
      hintText: 'Hint: Starts with "Look"',
    },
    {
      id: 'en_scramble_207',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'They are playing soccer.',
      tokens: ['They', 'are', 'playing', 'soccer', '.'],
      hintText: 'Hint: Starts with "They"',
    },
    {
      id: 'en_scramble_208',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 2,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'I love my lovely puppy.',
      tokens: ['I', 'love', 'my', 'lovely', 'puppy', '.'],
      hintText: 'Hint: Starts with "I"',
    },

    // --- Level 3: Sentence Scramble ---
    {
      id: 'en_scramble_301',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'There are three monkeys in the zoo.',
      tokens: ['There', 'are', 'three', 'monkeys', 'in', 'the', 'zoo', '.'],
      hintText: 'Hint: Starts with "There are"',
    },
    {
      id: 'en_scramble_302',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The green frog jumps into the water.',
      tokens: ['The', 'green', 'frog', 'jumps', 'into', 'the', 'water', '.'],
      hintText: 'Hint: What does the frog do?',
    },
    {
      id: 'en_scramble_303',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'My father likes drinking hot tea.',
      tokens: ['My', 'father', 'likes', 'drinking', 'hot', 'tea', '.'],
      hintText: 'Hint: Starts with "My father"',
    },
    {
      id: 'en_scramble_304',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'She puts the book on the desk.',
      tokens: ['She', 'puts', 'the', 'book', 'on', 'the', 'desk', '.'],
      hintText: 'Hint: Where does she put the book?',
    },
    {
      id: 'en_scramble_305',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'We eat lunch at twelve oclock.',
      tokens: ['We', 'eat', 'lunch', 'at', 'twelve', "o'clock", '.'],
      hintText: 'Hint: Starts with "We eat lunch"',
    },
    {
      id: 'en_scramble_306',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 3,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The cute rabbit has long white ears.',
      tokens: ['The', 'cute', 'rabbit', 'has', 'long', 'white', 'ears', '.'],
      hintText: 'Hint: The rabbit has...',
    },

    // --- Level 4: Sentence Scramble ---
    {
      id: 'en_scramble_401',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'I brush my teeth every morning.',
      tokens: ['I', 'brush', 'my', 'teeth', 'every', 'morning', '.'],
      hintText: 'Hint: Starts with "I"',
    },
    {
      id: 'en_scramble_402',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'The yellow duck is swimming in the pond.',
      tokens: ['The', 'yellow', 'duck', 'is', 'swimming', '.'],
      hintText: 'Hint: Starts with "The"',
    },
    {
      id: 'en_scramble_403',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'We play games in the classroom.',
      tokens: ['We', 'play', 'in', 'the', 'room', '.'],
      hintText: 'Hint: Starts with "We"',
    },
    {
      id: 'en_scramble_404',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'My brother can ride a bicycle.',
      tokens: ['My', 'brother', 'can', 'ride', 'a', 'bicycle', '.'],
      hintText: 'Hint: Starts with "My"',
    },
    {
      id: 'en_scramble_405',
      subject: 'english',
      category: 'sentence_scramble',
      type: 'sentence_scramble',
      difficulty: 4,
      prompt: 'Sentence Scramble: Put the words in the right order.',
      speakText: 'There is a rainbow in the sky.',
      tokens: ['There', 'is', 'a', 'rainbow', 'in', 'the', 'sky', '.'],
      hintText: 'Hint: Starts with "There"',
    },

    // --- Phonics & CVC Words ---
    {
      id: 'en_phonics_101',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Which word rhymes with "cat"?',
      speakText: 'Which word rhymes with cat?',
      options: ['hat', 'dog', 'sun', 'bed'],
      correctOptionIndex: 0,
      correctAnswer: 'hat',
      hintText: 'Hint: Ending with "-at"',
    },
    {
      id: 'en_phonics_102',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Which word begins with the sound /b/?',
      speakText: 'Which word begins with the sound b?',
      options: ['bat', 'cat', 'mat', 'pig'],
      correctOptionIndex: 0,
      correctAnswer: 'bat',
      hintText: 'Hint: Like /b/ /b/ ball',
    },
    {
      id: 'en_phonics_103',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'What is the vowel in "dog"?',
      speakText: 'What is the vowel letter in dog?',
      options: ['o', 'a', 'e', 'u'],
      correctOptionIndex: 0,
      correctAnswer: 'o',
      hintText: 'Hint: d - _ - g',
    },
    {
      id: 'en_phonics_104',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Which word ends with the sound /g/?',
      speakText: 'Which word ends with the sound g?',
      options: ['pig', 'pen', 'pan', 'cup'],
      correctOptionIndex: 0,
      correctAnswer: 'pig',
      hintText: 'Hint: p - i - g',
    },
    {
      id: 'en_phonics_201',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Which word rhymes with "sun"?',
      speakText: 'Which word rhymes with sun?',
      options: ['run', 'sit', 'red', 'top'],
      correctOptionIndex: 0,
      correctAnswer: 'run',
      hintText: 'Hint: Ending with "-un"',
    },
    {
      id: 'en_phonics_202',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'What is the middle vowel sound in "pin"?',
      speakText: 'What is the middle vowel letter in pin?',
      options: ['i', 'a', 'o', 'u'],
      correctOptionIndex: 0,
      correctAnswer: 'i',
      hintText: 'Hint: p - _ - n',
    },
    {
      id: 'en_phonics_203',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Which word starts with the /s/ sound?',
      speakText: 'Which word starts with s?',
      options: ['snake', 'tree', 'ball', 'fish'],
      correctOptionIndex: 0,
      correctAnswer: 'snake',
      hintText: 'Hint: /s/ /s/ snake',
    },
    {
      id: 'en_phonics_204',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Which word has the short /e/ sound?',
      speakText: 'Which word has the short e sound?',
      options: ['bed', 'bad', 'bud', 'box'],
      correctOptionIndex: 0,
      correctAnswer: 'bed',
      hintText: 'Hint: b - e - d',
    },
    {
      id: 'en_phonics_301',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Which word begins with the digraph "sh"?',
      speakText: 'Which word begins with s h?',
      options: ['ship', 'chip', 'whip', 'trip'],
      correctOptionIndex: 0,
      correctAnswer: 'ship',
      hintText: 'Hint: /sh/ sound as in shoe',
    },
    {
      id: 'en_phonics_302',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Which word begins with the "ch" sound?',
      speakText: 'Which word begins with c h?',
      options: ['chair', 'share', 'pair', 'bear'],
      correctOptionIndex: 0,
      correctAnswer: 'chair',
      hintText: 'Hint: /ch/ sound as in cheese',
    },
    {
      id: 'en_phonics_303',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Which word ends with the "th" sound?',
      speakText: 'Which word ends with t h?',
      options: ['bath', 'back', 'band', 'bank'],
      correctOptionIndex: 0,
      correctAnswer: 'bath',
      hintText: 'Hint: b - a - t - h',
    },
    {
      id: 'en_phonics_304',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Which word has a magic "e" making a long /a/ sound?',
      speakText: 'Which word has a long a sound with silent e?',
      options: ['cake', 'cat', 'cup', 'can'],
      correctOptionIndex: 0,
      correctAnswer: 'cake',
      hintText: 'Hint: c - a - k - e',
    },
    {
      id: 'en_phonics_401',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Which word starts with the voiced "th" sound as in "this"?',
      speakText: 'Which word starts with the voiced th sound?',
      options: ['that', 'thank', 'think', 'thumb'],
      correctOptionIndex: 0,
      correctAnswer: 'that',
      hintText: 'Hint: /th/ as in this, that, the',
    },
    {
      id: 'en_phonics_402',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Which word rhymes with "sing"?',
      speakText: 'Which word rhymes with sing?',
      options: ['ring', 'rag', 'run', 'red'],
      correctOptionIndex: 0,
      correctAnswer: 'ring',
      hintText: 'Hint: Ending in "-ing"',
    },
    {
      id: 'en_phonics_403',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Which word contains the vowel team "ea" (/ee/)?',
      speakText: 'Which word contains e a?',
      options: ['read', 'ride', 'rope', 'rude'],
      correctOptionIndex: 0,
      correctAnswer: 'read',
      hintText: 'Hint: r - e - a - d',
    },
    {
      id: 'en_phonics_404',
      subject: 'english',
      category: 'phonics',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Which word begins with the blend "fl"?',
      speakText: 'Which word begins with f l?',
      options: ['flag', 'frog', 'free', 'fast'],
      correctOptionIndex: 0,
      correctAnswer: 'flag',
      hintText: 'Hint: /fl/ sound as in fly',
    },

    // --- Sight Words ---
    {
      id: 'en_sight_101',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct word: "I ___ a student."',
      speakText: 'I blank a student.',
      options: ['am', 'is', 'are', 'be'],
      correctOptionIndex: 0,
      correctAnswer: 'am',
      hintText: 'Hint: "I" pairs with "am"',
    },
    {
      id: 'en_sight_102',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct word: "She ___ happy today."',
      speakText: 'She blank happy today.',
      options: ['is', 'are', 'am', 'were'],
      correctOptionIndex: 0,
      correctAnswer: 'is',
      hintText: 'Hint: "She" is singular',
    },
    {
      id: 'en_sight_103',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct article: "This is ___ apple."',
      speakText: 'This is blank apple.',
      options: ['an', 'a', 'the', 'on'],
      correctOptionIndex: 0,
      correctAnswer: 'an',
      hintText: 'Hint: "apple" starts with a vowel',
    },
    {
      id: 'en_sight_104',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct word: "Look at ___ red car."',
      speakText: 'Look at blank red car.',
      options: ['the', 'they', 'them', 'these'],
      correctOptionIndex: 0,
      correctAnswer: 'the',
      hintText: 'Hint: Definite article',
    },
    {
      id: 'en_sight_201',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct word: "We ___ playing in the park."',
      speakText: 'We blank playing in the park.',
      options: ['are', 'is', 'am', 'has'],
      correctOptionIndex: 0,
      correctAnswer: 'are',
      hintText: 'Hint: "We" pairs with "are"',
    },
    {
      id: 'en_sight_202',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct verb: "He ___ a new toy car."',
      speakText: 'He blank a new toy car.',
      options: ['has', 'have', 'having', 'are'],
      correctOptionIndex: 0,
      correctAnswer: 'has',
      hintText: 'Hint: 3rd person singular takes "has"',
    },
    {
      id: 'en_sight_203',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct word: "___ you like ice cream?"',
      speakText: 'Blank you like ice cream?',
      options: ['Do', 'Does', 'Is', 'Are'],
      correctOptionIndex: 0,
      correctAnswer: 'Do',
      hintText: 'Hint: Question for "you" in present tense',
    },
    {
      id: 'en_sight_204',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct word: "They ___ my classmates."',
      speakText: 'They blank my classmates.',
      options: ['are', 'is', 'was', 'has'],
      correctOptionIndex: 0,
      correctAnswer: 'are',
      hintText: 'Hint: Plural "They" takes "are"',
    },
    {
      id: 'en_sight_301',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the correct question word: "___ is your class teacher?"',
      speakText: 'Blank is your class teacher?',
      options: ['Who', 'What', 'Where', 'When'],
      correctOptionIndex: 0,
      correctAnswer: 'Who',
      hintText: 'Hint: Asking about a person',
    },
    {
      id: 'en_sight_302',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the correct modal verb: "Birds can ___ in the sky."',
      speakText: 'Birds can blank in the sky.',
      options: ['fly', 'flying', 'flies', 'flew'],
      correctOptionIndex: 0,
      correctAnswer: 'fly',
      hintText: 'Hint: "can" is followed by base verb',
    },
    {
      id: 'en_sight_303',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the correct form: "There ___ many books on the shelf."',
      speakText: 'There blank many books on the shelf.',
      options: ['are', 'is', 'has', 'was'],
      correctOptionIndex: 0,
      correctAnswer: 'are',
      hintText: 'Hint: "many books" is plural',
    },
    {
      id: 'en_sight_304',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the preposition: "She likes to play ___ her brother."',
      speakText: 'She likes to play blank her brother.',
      options: ['with', 'of', 'for', 'to'],
      correctOptionIndex: 0,
      correctAnswer: 'with',
      hintText: 'Hint: Together with someone',
    },
    {
      id: 'en_sight_401',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the question word: "___ time is it now?"',
      speakText: 'Blank time is it now?',
      options: ['What', 'Where', 'Who', 'Why'],
      correctOptionIndex: 0,
      correctAnswer: 'What',
      hintText: 'Hint: "What time is it?"',
    },
    {
      id: 'en_sight_402',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the conjunction: "We stayed home ___ it was raining."',
      speakText: 'We stayed home blank it was raining.',
      options: ['because', 'although', 'but', 'so'],
      correctOptionIndex: 0,
      correctAnswer: 'because',
      hintText: 'Hint: Explains the reason',
    },
    {
      id: 'en_sight_403',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the correct verb: "He does not ___ any pencils left."',
      speakText: 'He does not blank any pencils left.',
      options: ['have', 'has', 'had', 'having'],
      correctOptionIndex: 0,
      correctAnswer: 'have',
      hintText: 'Hint: "does not" takes base verb "have"',
    },
    {
      id: 'en_sight_404',
      subject: 'english',
      category: 'sight_word',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the correct word: "___ shoes are these under the bed?"',
      speakText: 'Blank shoes are these under the bed?',
      options: ['Whose', 'Who', 'Where', 'Which'],
      correctOptionIndex: 0,
      correctAnswer: 'Whose',
      hintText: 'Hint: Asking about ownership',
    },

    // --- Plurals (Singular & Plural) ---
    {
      id: 'en_plural_101',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Complete the plural: "one cat, two ___"',
      speakText: 'one cat, two what?',
      options: ['cats', 'cates', 'cat', 'cating'],
      correctOptionIndex: 0,
      correctAnswer: 'cats',
      hintText: 'Hint: Add "-s"',
    },
    {
      id: 'en_plural_102',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Complete the plural: "one book, three ___"',
      speakText: 'one book, three what?',
      options: ['books', 'bookes', 'book', 'booking'],
      correctOptionIndex: 0,
      correctAnswer: 'books',
      hintText: 'Hint: Add "-s"',
    },
    {
      id: 'en_plural_103',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Complete the plural: "one dog, four ___"',
      speakText: 'one dog, four what?',
      options: ['dogs', 'doges', 'dog', 'doging'],
      correctOptionIndex: 0,
      correctAnswer: 'dogs',
      hintText: 'Hint: Add "-s"',
    },
    {
      id: 'en_plural_201',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Complete the plural: "one apple, five ___"',
      speakText: 'one apple, five what?',
      options: ['apples', 'appless', 'apple', 'apply'],
      correctOptionIndex: 0,
      correctAnswer: 'apples',
      hintText: 'Hint: Add "-s"',
    },
    {
      id: 'en_plural_202',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Complete the plural: "one bus, two ___"',
      speakText: 'one bus, two what?',
      options: ['buses', 'buss', 'bus', 'busies'],
      correctOptionIndex: 0,
      correctAnswer: 'buses',
      hintText: 'Hint: Words ending in -s add "-es"',
    },
    {
      id: 'en_plural_203',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Complete the plural: "one box, three ___"',
      speakText: 'one box, three what?',
      options: ['boxes', 'boxs', 'box', 'boxing'],
      correctOptionIndex: 0,
      correctAnswer: 'boxes',
      hintText: 'Hint: Words ending in -x add "-es"',
    },
    {
      id: 'en_plural_301',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Complete the plural: "one glass, four ___"',
      speakText: 'one glass, four what?',
      options: ['glasses', 'glasss', 'glass', 'glassing'],
      correctOptionIndex: 0,
      correctAnswer: 'glasses',
      hintText: 'Hint: Add "-es" after -ss',
    },
    {
      id: 'en_plural_302',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Complete the plural: "one dish, two ___"',
      speakText: 'one dish, two what?',
      options: ['dishes', 'dishs', 'dish', 'dishing'],
      correctOptionIndex: 0,
      correctAnswer: 'dishes',
      hintText: 'Hint: Add "-es" after -sh',
    },
    {
      id: 'en_plural_303',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Complete the plural: "one watch, three ___"',
      speakText: 'one watch, three what?',
      options: ['watches', 'watchs', 'watch', 'watching'],
      correctOptionIndex: 0,
      correctAnswer: 'watches',
      hintText: 'Hint: Add "-es" after -ch',
    },
    {
      id: 'en_plural_401',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Complete the irregular plural: "one child, two ___"',
      speakText: 'one child, two what?',
      options: ['children', 'childs', 'childes', 'childrens'],
      correctOptionIndex: 0,
      correctAnswer: 'children',
      hintText: 'Hint: Irregular plural of child',
    },
    {
      id: 'en_plural_402',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Complete the irregular plural: "one foot, two ___"',
      speakText: 'one foot, two what?',
      options: ['feet', 'foots', 'footes', 'feets'],
      correctOptionIndex: 0,
      correctAnswer: 'feet',
      hintText: 'Hint: Change "oo" to "ee"',
    },
    {
      id: 'en_plural_403',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Complete the irregular plural: "one tooth, three ___"',
      speakText: 'one tooth, three what?',
      options: ['teeth', 'tooths', 'toothes', 'teeths'],
      correctOptionIndex: 0,
      correctAnswer: 'teeth',
      hintText: 'Hint: Change "oo" to "ee"',
    },

    // --- Prepositions ---
    {
      id: 'en_prep_101',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the preposition: "The cat is sitting ___ the mat."',
      speakText: 'The cat is sitting blank the mat.',
      options: ['on', 'in', 'under', 'at'],
      correctOptionIndex: 0,
      correctAnswer: 'on',
      hintText: 'Hint: On top of a surface',
    },
    {
      id: 'en_prep_102',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the preposition: "The fish is swimming ___ the water."',
      speakText: 'The fish is swimming blank the water.',
      options: ['in', 'on', 'under', 'for'],
      correctOptionIndex: 0,
      correctAnswer: 'in',
      hintText: 'Hint: Inside the water',
    },
    {
      id: 'en_prep_201',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the preposition: "The slippers are ___ the bed."',
      speakText: 'The slippers are blank the bed.',
      options: ['under', 'in', 'on', 'with'],
      correctOptionIndex: 0,
      correctAnswer: 'under',
      hintText: 'Hint: Below the bed',
    },
    {
      id: 'en_prep_202',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the preposition: "The apple is ___ the tree branch."',
      speakText: 'The apple is blank the tree branch.',
      options: ['on', 'in', 'under', 'to'],
      correctOptionIndex: 0,
      correctAnswer: 'on',
      hintText: 'Hint: Resting on the branch',
    },
    {
      id: 'en_prep_301',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the preposition: "The rabbit is hiding ___ the big tree."',
      speakText: 'The rabbit is hiding blank the big tree.',
      options: ['behind', 'in', 'on', 'with'],
      correctOptionIndex: 0,
      correctAnswer: 'behind',
      hintText: 'Hint: At the back of the tree',
    },
    {
      id: 'en_prep_302',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 3,
      prompt: 'Choose the preposition: "Our school is ___ the MTR station."',
      speakText: 'Our school is blank the MTR station.',
      options: ['near', 'of', 'on', 'into'],
      correctOptionIndex: 0,
      correctAnswer: 'near',
      hintText: 'Hint: Close to',
    },
    {
      id: 'en_prep_401',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the preposition: "The ruler is ___ the book and the pencil."',
      speakText: 'The ruler is blank the book and the pencil.',
      options: ['between', 'among', 'behind', 'under'],
      correctOptionIndex: 0,
      correctAnswer: 'between',
      hintText: 'Hint: In the middle of two things',
    },
    {
      id: 'en_prep_402',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 4,
      prompt: 'Choose the preposition: "The puppy is sleeping ___ the door."',
      speakText: 'The puppy is sleeping blank the door.',
      options: ['next to', 'near to', 'inside to', 'between to'],
      correctOptionIndex: 0,
      correctAnswer: 'next to',
      hintText: 'Hint: Beside the door',
    },

    // --- Pronouns & Verb To Be ---
    {
      id: 'en_pronoun_101',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct pronoun: "Tom is a boy. ___ is seven years old."',
      speakText: 'Tom is a boy. Blank is seven years old.',
      options: ['He', 'She', 'It', 'They'],
      correctOptionIndex: 0,
      correctAnswer: 'He',
      hintText: 'Hint: Tom is a boy',
    },
    {
      id: 'en_pronoun_102',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct pronoun: "Amy is singing. ___ has a sweet voice."',
      speakText: 'Amy is singing. Blank has a sweet voice.',
      options: ['She', 'He', 'It', 'They'],
      correctOptionIndex: 0,
      correctAnswer: 'She',
      hintText: 'Hint: Amy is a girl',
    },
    {
      id: 'en_pronoun_103',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct pronoun: "The bird is in the tree. ___ can fly high."',
      speakText: 'The bird is in the tree. Blank can fly high.',
      options: ['It', 'He', 'She', 'We'],
      correctOptionIndex: 0,
      correctAnswer: 'It',
      hintText: 'Hint: The bird is an animal',
    },
    {
      id: 'en_pronoun_201',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct pronoun: "Ben and Tim are friends. ___ play together."',
      speakText: 'Ben and Tim are friends. Blank play together.',
      options: ['They', 'We', 'He', 'She'],
      correctOptionIndex: 0,
      correctAnswer: 'They',
      hintText: 'Hint: Two people (plural)',
    },
    {
      id: 'en_verb_101',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct verb: "I ___ a primary one student."',
      speakText: 'I blank a primary one student.',
      options: ['am', 'is', 'are', 'be'],
      correctOptionIndex: 0,
      correctAnswer: 'am',
      hintText: 'Hint: "I" pairs with "am"',
    },
    {
      id: 'en_verb_102',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the correct verb: "The apples ___ sweet and red."',
      speakText: 'The apples blank sweet and red.',
      options: ['are', 'is', 'am', 'be'],
      correctOptionIndex: 0,
      correctAnswer: 'are',
      hintText: 'Hint: "apples" is plural',
    },
    {
      id: 'en_verb_201',
      subject: 'english',
      category: 'grammar',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the correct verb: "Miss Lee ___ our English teacher."',
      speakText: 'Miss Lee blank our English teacher.',
      options: ['is', 'are', 'am', 'were'],
      correctOptionIndex: 0,
      correctAnswer: 'is',
      hintText: 'Hint: Singular third person',
    },
    {
      id: 'en_plural_105',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the plural: "one dish, two ___"',
      speakText: 'one dish, two what?',
      options: ['dishes', 'dishs', 'dishies', 'dish'],
      correctOptionIndex: 0,
      correctAnswer: 'dishes',
      hintText: 'Hint: Add -es after -sh',
    },
    {
      id: 'en_plural_104',
      subject: 'english',
      category: 'plural',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the plural: "one watch, three ___"',
      speakText: 'one watch, three what?',
      options: ['watches', 'watchs', 'watchies', 'watchess'],
      correctOptionIndex: 0,
      correctAnswer: 'watches',
      hintText: 'Hint: Add -es after -ch',
    },
    {
      id: 'en_prep_103',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 1,
      prompt: 'Choose the preposition: "The pencil is ___ the pencil case."',
      speakText: 'The pencil is blank the pencil case.',
      options: ['in', 'on', 'under', 'at'],
      correctOptionIndex: 0,
      correctAnswer: 'in',
      hintText: 'Hint: Inside the pencil case',
    },
    {
      id: 'en_prep_203',
      subject: 'english',
      category: 'preposition',
      type: 'multiple_choice',
      difficulty: 2,
      prompt: 'Choose the preposition: "The clock is hanging ___ the wall."',
      speakText: 'The clock is hanging blank the wall.',
      options: ['on', 'in', 'under', 'to'],
      correctOptionIndex: 0,
      correctAnswer: 'on',
      hintText: 'Hint: On the surface of the wall',
    },
  ];

  static readonly ALL_ITEMS: readonly CurriculumItem[] = [
    ...CurriculumBank.CHINESE_BANK,
    ...CurriculumBank.ENGLISH_BANK,
  ];

  /**
   * Retrieves items matching subject, difficulty, and optional category.
   */
  static getItems(
    subject?: 'chinese' | 'english',
    difficulty?: number,
    category?: string
  ): CurriculumItem[] {
    let pool: readonly CurriculumItem[] = this.ALL_ITEMS;

    if (subject) {
      pool = pool.filter((item) => item.subject === subject);
    }
    if (difficulty !== undefined) {
      pool = pool.filter((item) => item.difficulty === difficulty);
    }
    if (category) {
      pool = pool.filter((item) => item.category === category);
    }

    return [...pool];
  }

  /**
   * Finds an item by its unique ID.
   */
  static getItemById(id: string): CurriculumItem | undefined {
    return this.ALL_ITEMS.find((item) => item.id === id);
  }
}
