export type WardrobeCategory = 'dress' | 'top' | 'bottom' | 'accessory';
export type WardrobeFilter = WardrobeCategory | 'all' | 'owned';

export interface WardrobeItem {
  id: string;
  name: string;
  nameEn: string;
  category: WardrobeCategory;
  costCoins: number;
  costGems: number;
  description: string;
  perkDescription: string;
  icon: string;
  tint?: number;
  speakEn: string;
  speakZh: string;
}

export const WARDROBE_ITEMS: readonly WardrobeItem[] = [
  // --- 👗 連身裙 / 洋裝 / 套裝 (Dresses) ---
  {
    id: 'princess_dress',
    name: '夢幻粉紅公主裙',
    nameEn: 'Princess Dress',
    category: 'dress',
    costCoins: 250,
    costGems: 25,
    description: '飄逸甜美的粉紅公主連身裙，帶有星光亮片。',
    perkDescription: '✨ 走路自帶粉紅星光軌跡',
    icon: '👗',
    tint: 0xffb6c1,
    speakEn: 'Princess Dress',
    speakZh: '公主連身裙',
  },
  {
    id: 'scholar_robe',
    name: '升小一榮譽學士袍',
    nameEn: 'Scholar Gown',
    category: 'dress',
    costCoins: 300,
    costGems: 30,
    description: '象徵小一卓越成就的榮譽學士袍，金邊刺繡。',
    perkDescription: '🎓 答對題目金幣結算 +1',
    icon: '👘',
    tint: 0x334466,
    speakEn: 'Scholar Gown',
    speakZh: '榮譽學士袍',
  },
  {
    id: 'dino_onesie',
    name: '萌萌小恐龍連身衣',
    nameEn: 'Dino Onesie',
    category: 'dress',
    costCoins: 200,
    costGems: 20,
    description: '綠色恐龍造型連身服，背部帶有軟綿綿背鰭！',
    perkDescription: '🦖 撞石頭減速時間 -30%',
    icon: '🦖',
    tint: 0x77dd77,
    speakEn: 'Dino Onesie',
    speakZh: '小恐龍連身衣',
  },
  {
    id: 'magic_robe',
    name: '星光魔法學徒袍',
    nameEn: 'Magic Robe',
    category: 'dress',
    costCoins: 280,
    costGems: 28,
    description: '深藍色繡滿繁星的魔法長袍，飄逸神秘。',
    perkDescription: '✨ 全域吸金半徑 +30px',
    icon: '🧙‍♀️',
    tint: 0x4b0082,
    speakEn: 'Magic Robe',
    speakZh: '魔法袍',
  },

  // --- 👕 潮流上衣 (Tops) ---
  {
    id: 'sailor_top',
    name: '天星小輪水手襯衫',
    nameEn: 'Sailor Shirt',
    category: 'top',
    costCoins: 80,
    costGems: 8,
    description: '經典維港水手藍白條紋水手服，清爽活潑。',
    perkDescription: '⚓ 經典香港維港風采',
    icon: '👕',
    tint: 0x2266aa,
    speakEn: 'Sailor Shirt',
    speakZh: '水手襯衫',
  },
  {
    id: 'hk_school_shirt',
    name: '經典名校白色校服衫',
    nameEn: 'School Shirt',
    category: 'top',
    costCoins: 60,
    costGems: 6,
    description: '整潔筆挺的純白校服襯衫，附有校章口袋。',
    perkDescription: '🏫 香港校園小一生必備',
    icon: '👔',
    tint: 0xf8f9fa,
    speakEn: 'School Shirt',
    speakZh: '白色校服衫',
  },
  {
    id: 'sport_jersey',
    name: '活力運動藍色T恤',
    nameEn: 'Sport Jersey',
    category: 'top',
    costCoins: 50,
    costGems: 5,
    description: '透氣排汗的運動短袖T恤，奔跑更輕快。',
    perkDescription: '⚽ 跑酷起步加速更靈敏',
    icon: '🎽',
    tint: 0x00a8ff,
    speakEn: 'Sport Jersey',
    speakZh: '運動T恤',
  },
  {
    id: 'hoodie_star',
    name: '閃爍星光連帽衛衣',
    nameEn: 'Star Hoodie',
    category: 'top',
    costCoins: 90,
    costGems: 9,
    description: '暖笠笠的黃色星星連帽衫，潮流保暖。',
    perkDescription: '🌟 跑酷跳躍時爆發微小星光',
    icon: '🧥',
    tint: 0xffaa00,
    speakEn: 'Star Hoodie',
    speakZh: '星光衛衣',
  },

  // --- 👖 褲子與短裙 (Bottoms / Skirts) ---
  {
    id: 'pleated_skirt',
    name: '英倫風百褶短裙',
    nameEn: 'Pleated Skirt',
    category: 'bottom',
    costCoins: 60,
    costGems: 6,
    description: '優雅的深藍色百褶裙，走動時靈動飄揚。',
    perkDescription: '🎀 奔跑跳躍靈活自如',
    icon: '🩳',
    tint: 0x1e3799,
    speakEn: 'Pleated Skirt',
    speakZh: '百褶短裙',
  },
  {
    id: 'denim_shorts',
    name: '陽光休閒牛仔短褲',
    nameEn: 'Denim Shorts',
    category: 'bottom',
    costCoins: 50,
    costGems: 5,
    description: '耐磨舒適的淺藍色牛仔短褲，探險好搭檔。',
    perkDescription: '👖 舒適耐穿，隨心奔跑',
    icon: '👖',
    tint: 0x4a69bd,
    speakEn: 'Denim Shorts',
    speakZh: '牛仔短褲',
  },
  {
    id: 'sport_shorts',
    name: '活力運動短褲',
    nameEn: 'Sport Shorts',
    category: 'bottom',
    costCoins: 40,
    costGems: 4,
    description: '輕巧吸汗的白邊運動短褲。',
    perkDescription: '🏃 跑速微量提升 +3%',
    icon: '🩲',
    tint: 0x0c2461,
    speakEn: 'Sport Shorts',
    speakZh: '運動短褲',
  },
  {
    id: 'magic_tutu',
    name: '繁星蓬蓬夢幻紗裙',
    nameEn: 'Starry Tutu',
    category: 'bottom',
    costCoins: 100,
    costGems: 10,
    description: '層層疊疊的粉紫蓬蓬紗裙，宛如芭蕾精靈。',
    perkDescription: '✨ 空中跳躍下落更輕盈',
    icon: '🩰',
    tint: 0xe056fd,
    speakEn: 'Starry Tutu',
    speakZh: '夢幻紗裙',
  },

  // --- 🎀 飾品與配件 (Accessories) ---
  {
    id: 'angel_wings',
    name: '潔白天使羽翼',
    nameEn: 'Angel Wings',
    category: 'accessory',
    costCoins: 150,
    costGems: 15,
    description: '背後展開的聖潔雙翼，起跳時散落羽毛微粒！',
    perkDescription: '🪶 二段跳高度額外提升 +15%',
    icon: '🪽',
    tint: 0xffffff,
    speakEn: 'Angel Wings',
    speakZh: '天使羽翼',
  },
  {
    id: 'cat_ears',
    name: '萌萌貓耳髮箍',
    nameEn: 'Cat Ears',
    category: 'accessory',
    costCoins: 60,
    costGems: 6,
    description: '可愛的立體貓耳朵，會隨跳躍輕輕晃動。',
    perkDescription: '🐱 喵～可愛度滿分！',
    icon: '🐱',
    tint: 0xff9ff3,
    speakEn: 'Cat Ears',
    speakZh: '貓耳髮箍',
  },
  {
    id: 'scholar_cap',
    name: '小一榮譽學士帽',
    nameEn: 'Scholar Cap',
    category: 'accessory',
    costCoins: 80,
    costGems: 8,
    description: '端莊的黑色四方帽，附有飄逸金黃色流蘇。',
    perkDescription: '🎓 小一升夢榮譽象徵',
    icon: '🎓',
    tint: 0x2c3e50,
    speakEn: 'Scholar Cap',
    speakZh: '學士四方帽',
  },
  {
    id: 'tram_hat',
    name: '叮叮車可愛車長帽',
    nameEn: 'Tram Captain Hat',
    category: 'accessory',
    costCoins: 70,
    costGems: 7,
    description: '懷舊復古的綠色叮叮電車車長大蓋帽。',
    perkDescription: '🚋 香港本土經典懷舊',
    icon: '🧢',
    tint: 0x10ac84,
    speakEn: 'Tram Captain Hat',
    speakZh: '車長大蓋帽',
  },
  {
    id: 'star_glasses',
    name: '智慧小博士星光眼鏡',
    nameEn: 'Smart Glasses',
    category: 'accessory',
    costCoins: 50,
    costGems: 5,
    description: '圓圓的金色復古黑框眼鏡，充滿學霸氣質。',
    perkDescription: '👓 題目關鍵字辨識更專注',
    icon: '👓',
    tint: 0xf1c40f,
    speakEn: 'Smart Glasses',
    speakZh: '小博士眼鏡',
  },
  {
    id: 'star_backpack',
    name: '星星探險小背囊',
    nameEn: 'Star Backpack',
    category: 'accessory',
    costCoins: 80,
    costGems: 8,
    description: '黃色星星造型背囊，奔跑時灑落金色星塵。',
    perkDescription: '🎒 跑酷金幣吸取半徑 +25px',
    icon: '🎒',
    tint: 0xf39c12,
    speakEn: 'Star Backpack',
    speakZh: '星星小背囊',
  },
];

export function getWardrobeItemsForFilter(
  items: readonly WardrobeItem[],
  filter: WardrobeFilter,
  ownedIds: readonly string[]
): readonly WardrobeItem[] {
  if (filter === 'all') return items;
  if (filter === 'owned') return items.filter(item => ownedIds.includes(item.id));
  return items.filter(item => item.category === filter);
}
