export const CHINESE_SPACE_COPY = {
  title: '中文字太空保衛戰',
  subtitle: '聽清楚，射中正確中文字！',
  start: '選擇篇章',
  badges: '兌換徽章',
  exit: '返回主頁',
  chapterTitle: '揀一個學習篇章',
  tutorialTitle: '飛行員教學',
  tutorial: '先聽聲音，再移動戰機，射中啱嘅中文字。',
  tutorialStart: '明白，開始！',
  listen: '聽緊字音⋯⋯',
  retryAudio: '再聽一次',
  fire: '開火',
  moveLeft: '向左',
  moveRight: '向右',
  question: '題目',
  hp: '生命值',
  gems: '太空寶石',
  correct: '答啱！',
  wrong: '小心！再聽一次。',
  timeout: '時間到！再試一次。',
  result: '任務完成！',
  gameOver: '戰機需要維修',
  resultCorrect: '答啱題目',
  resultAverage: '平均反應時間',
  resultHp: '剩餘生命值',
  reward: '獲得 5 顆太空寶石',
  playAgain: '再玩一次',
  chooseChapter: '選擇篇章',
  backHome: '返回主頁',
  repair: '再試一次',
  noGems: '太空寶石未夠。',
  redeemed: '徽章兌換成功！',
  owned: '已擁有',
  price: '需要',
  orientation: '請將裝置橫向使用',
  loading: '太空站準備中⋯⋯',
};
